from .diff import ProjectDiffValidationError, diff_bundles, diff_projects
from .executor import RuleExecutionResult, RuleExecutionTrace, execute_rule_stack
from .preview import PreviewImageResult, PreviewRenderResult, render_preview, render_preview_image
from .regions import normalized_polygon_to_pixels, region_influence, resolve_region_influence
from .render import (
    RenderExecutionError,
    RenderInputError,
    RenderPlan,
    RenderResult,
    apply_crop,
    execute_project_image,
    plan_render,
    render_bundle_output,
    render_output,
)
from .selection import apply_weighted_channel_transform, brightness_weight, colour_weight
from .semantic import dark_dust_influence, semantic_target_influence, star_influence
from .sources import (
    PreparedSourcesResult,
    SourceAlignmentReport,
    SourcePreparationError,
    clear_prepared_sources_cache,
    inspect_sources,
    write_aligned_bundle,
)
from .validation import (
    EXIT_INPUT_ERROR,
    EXIT_RENDER_ERROR,
    EXIT_RUNTIME_ERROR,
    EXIT_VALIDATION_ERROR,
    EXIT_VALIDATION_SUCCESS,
    ValidationIssue,
    ValidationReport,
    ValidationRuntimeError,
    load_valid_project_bundle,
    validate_project,
)

__all__ = [
    "EXIT_INPUT_ERROR",
    "EXIT_RUNTIME_ERROR",
    "EXIT_RENDER_ERROR",
    "EXIT_VALIDATION_ERROR",
    "EXIT_VALIDATION_SUCCESS",
    "PreviewRenderResult",
    "PreviewImageResult",
    "ProjectDiffValidationError",
    "RenderExecutionError",
    "RenderInputError",
    "RenderPlan",
    "RenderResult",
    "PreparedSourcesResult",
    "RuleExecutionResult",
    "RuleExecutionTrace",
    "SourceAlignmentReport",
    "SourcePreparationError",
    "clear_prepared_sources_cache",
    "ValidationIssue",
    "ValidationReport",
    "ValidationRuntimeError",
    "apply_crop",
    "apply_weighted_channel_transform",
    "brightness_weight",
    "diff_projects",
    "diff_bundles",
    "dark_dust_influence",
    "colour_weight",
    "clear_prepared_sources_cache",
    "execute_project_image",
    "execute_rule_stack",
    "inspect_sources",
    "load_valid_project_bundle",
    "normalized_polygon_to_pixels",
    "plan_render",
    "region_influence",
    "render_bundle_output",
    "render_output",
    "render_preview",
    "render_preview_image",
    "resolve_region_influence",
    "semantic_target_influence",
    "star_influence",
    "validate_project",
    "write_aligned_bundle",
]
